const tasks = [
  {
    title: 'Task One',
    description: 'First sample task',
    status: 'PENDING',
    priority: 'HIGH',
    dueDate: new Date('2024-01-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Two',
    description: 'Another test task',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    dueDate: new Date('2024-02-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Three',
    description: 'Third example task',
    status: 'PENDING',
    priority: 'LOW',
    dueDate: new Date('2024-03-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Four',
    description: 'Fourth test task',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: new Date('2024-04-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Five',
    description: 'Fifth test task',
    status: 'PENDING',
    priority: 'MEDIUM',
    dueDate: new Date('2024-05-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Six',
    description: 'Sixth sample task',
    status: 'COMPLETED',
    priority: 'LOW',
    dueDate: new Date('2024-06-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Seven',
    description: 'Seventh test task',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: new Date('2024-07-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Eight',
    description: 'Eighth test task',
    status: 'PENDING',
    priority: 'MEDIUM',
    dueDate: new Date('2024-08-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Nine',
    description: 'Ninth test task',
    status: 'PENDING',
    priority: 'LOW',
    dueDate: new Date('2024-09-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Ten',
    description: 'Tenth test task',
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: new Date('2024-10-01T00:00:00Z'),
    readOnly: true,
  },
  {
    title: 'Task Eleven',
    description: 'Eleventh sample task',
    status: 'PENDING',
    priority: 'MEDIUM',
    dueDate: new Date('2024-11-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Twelve',
    description: 'Twelfth sample task',
    status: 'IN_PROGRESS',
    priority: 'LOW',
    dueDate: new Date('2024-12-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Thirteen',
    description: 'Thirteenth test task',
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: new Date('2025-01-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Fourteen',
    description: 'Fourteenth test task',
    status: 'PENDING',
    priority: 'MEDIUM',
    dueDate: new Date('2025-02-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Fifteen',
    description: 'Fifteenth test task',
    status: 'IN_PROGRESS',
    priority: 'LOW',
    dueDate: new Date('2025-03-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Sixteen',
    description: 'Sixteenth test task',
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: new Date('2025-04-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Seventeen',
    description: 'Seventeenth sample task',
    status: 'PENDING',
    priority: 'MEDIUM',
    dueDate: new Date('2025-05-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Eighteen',
    description: 'Eighteenth sample task',
    status: 'PENDING',
    priority: 'LOW',
    dueDate: new Date('2025-06-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Nineteen',
    description: 'Nineteenth test task',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: new Date('2025-07-01T00:00:00Z'),
    readOnly: false,
  },
  {
    title: 'Task Twenty',
    description: 'Twentieth test task',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    dueDate: new Date('2025-08-01T00:00:00Z'),
    readOnly: false,
  },
];

export default tasks;
