import { CreateTaskDTO } from '../src/dtos/create-task.dto';

const tasks: CreateTaskDTO[] = [
  {
    title: 'Task One',
    description: 'First sample task',
    status: 'TO_DO',
    priority: 'HIGH',
    dueDate: '2024-01-01T00:00:00Z',
  },
  {
    title: 'Task Two',
    description: 'Second sample task',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    dueDate: '2024-02-01T00:00:00Z',
  },
  {
    title: 'Task Three',
    description: 'Third sample task',
    status: 'PENDING',
    priority: 'LOW',
    dueDate: '2024-03-01T00:00:00Z',
  },
  {
    title: 'Task Four',
    description: 'Fourth sample task',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: '2024-04-01T00:00:00Z',
  },
  {
    title: 'Task Five',
    description: 'Fifth sample task',
    status: 'TO_DO',
    priority: 'MEDIUM',
    dueDate: '2024-05-01T00:00:00Z',
  },
  {
    title: 'Task Six',
    description: 'Sixth sample task',
    status: 'COMPLETED',
    priority: 'LOW',
    dueDate: '2024-06-01T00:00:00Z',
  },
  {
    title: 'Task Seven',
    description: 'Seventh sample task',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: '2024-07-01T00:00:00Z',
  },
  {
    title: 'Task Eight',
    description: 'Eighth sample task',
    status: 'TO_DO',
    priority: 'MEDIUM',
    dueDate: '2024-08-01T00:00:00Z',
  },
  {
    title: 'Task Nine',
    description: 'Ninth sample task',
    status: 'PENDING',
    priority: 'LOW',
    dueDate: '2024-09-01T00:00:00Z',
  },
  {
    title: 'Task Ten',
    description: 'Tenth sample task',
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: '2024-10-01T00:00:00Z',
  },
  {
    title: 'Task Eleven',
    description: 'Eleventh sample task',
    status: 'TO_DO',
    priority: 'MEDIUM',
    dueDate: '2024-11-01T00:00:00Z',
  },
  {
    title: 'Task Twelve',
    description: 'Twelfth sample task',
    status: 'IN_PROGRESS',
    priority: 'LOW',
    dueDate: '2024-12-01T00:00:00Z',
  },
  {
    title: 'Task Thirteen',
    description: 'Thirteenth sample task',
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: '2025-01-01T00:00:00Z',
  },
  {
    title: 'Task Fourteen',
    description: 'Fourteenth sample task',
    status: 'PENDING',
    priority: 'MEDIUM',
    dueDate: '2025-02-01T00:00:00Z',
  },
  {
    title: 'Task Fifteen',
    description: 'Fifteenth sample task',
    status: 'IN_PROGRESS',
    priority: 'LOW',
    dueDate: '2025-03-01T00:00:00Z',
  },
  {
    title: 'Task Sixteen',
    description: 'Sixteenth sample task',
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: '2025-04-01T00:00:00Z',
  },
  {
    title: 'Task Seventeen',
    description: 'Seventeenth sample task',
    status: 'TO_DO',
    priority: 'MEDIUM',
    dueDate: '2025-05-01T00:00:00Z',
  },
  {
    title: 'Task Eighteen',
    description: 'Eighteenth sample task',
    status: 'PENDING',
    priority: 'LOW',
    dueDate: '2025-06-01T00:00:00Z',
  },
  {
    title: 'Task Nineteen',
    description: 'Nineteenth sample task',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: '2025-07-01T00:00:00Z',
  },
  {
    title: 'Task Twenty',
    description: 'Twentieth sample task',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    dueDate: '2025-08-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-One',
    description: 'Twenty-first sample task',
    status: 'TO_DO',
    priority: 'MEDIUM',
    dueDate: '2024-11-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-Two',
    description: 'Twenty-second sample task',
    status: 'IN_PROGRESS',
    priority: 'LOW',
    dueDate: '2024-12-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-Three',
    description: 'Twenty-third sample task',
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: '2025-01-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-Four',
    description: 'Twenty-fourth sample task',
    status: 'PENDING',
    priority: 'MEDIUM',
    dueDate: '2025-02-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-Five',
    description: 'Twenty-fifth sample task',
    status: 'IN_PROGRESS',
    priority: 'LOW',
    dueDate: '2025-03-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-Six',
    description: 'Twenty-sixth sample task',
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: '2025-04-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-Seven',
    description: 'Twenty-seventh sample task',
    status: 'TO_DO',
    priority: 'MEDIUM',
    dueDate: '2025-05-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-Eight',
    description: 'Twenty-eighth sample task',
    status: 'PENDING',
    priority: 'LOW',
    dueDate: '2025-06-01T00:00:00Z',
  },
  {
    title: 'Task Twenty-Nine',
    description: 'Twenty-ninth sample task',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: '2025-07-01T00:00:00Z',
  },
  {
    title: 'Task Thirty',
    description: 'Thirtieth sample task',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    dueDate: '2025-08-01T00:00:00Z',
  },
];

export default tasks;
