# .github/workflows/backend_ci.yml
name: Backend CI Pipeline

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
    
jobs:
  backend_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: npm ci

      - name: Run Backend Lint Check
        run: npm run lint:check

      - name: Run Backend Prettier Check
        run: npm run prettier:check

      - name: Run Backend Tests
        run: npm run test
