# .github/workflows/frontend_ci.yml
name: Frontend CI Pipeline

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
    
jobs:
  frontend_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Run Frontend Lint Check
        run: npm run lint:check

      - name: Run Frontend Prettier Check
        run: npm run prettier:check

      # - name: Run Frontend Tests
      #   run: npm run test
